### PR TITLE
Automatic token refresh

### PR DESCRIPTION
**Pull request by yinzara**
Still needs tests

### CODE REVIEW

**Comment by joshcanhelp** [comment]
@yinzara - Thanks for this! Can you please fill out the PR template that was loaded when you created this?

**Comment by yinzara** [comment]
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

While the Auth0 PHP library provides the ability to refresh an access token, there is no method to calculate when this is necessary nor is there a way to automatically renew a token using a refresh_token when necessary.

This PR adds a new "expiresAt" persisted property to the Auth0 client that's calculated during token exchange (either during initial code exchange or refresh exchange) using the "expires_in" response parameter which is currently ignored.

If this parameter isn't present (for example, if using a different OAuth provider than Auth0), the 'exp' claim of the id_token is used to calculate expiration.

When this new property exists and a refreshToken is also present, the "getAccesToken", "getUser" or "getRefreshToken" functions now will call "refreshTokens" if the expiration has been reached before returning their values.

This functionality does not get persisted between page refreshes unless the new "persist_expires_at" option is specified as true.  

By specifying this option as true and adding "offline_access" to the requested scopes, all calls to 'getAccessToken' will return a valid non-expired access token and calls to "getUser" function will always return the most recent decoded user info (either from the id token or user info endpoint).

auth.com/docs should be updated to include the new option.

### Testing

- [X] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [X] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

**Comment by yinzara** [comment]
I added the ability to mock the "time()" function to allow for testing this new functionality.

I'm still having a problem where my new test case passes when I run it within my IDE but when I run it from the CLI, it fails as if the new time mocking isn't working when running from the CLI.

I'll get back with more info.

**Comment by joshcanhelp** [comment]
@yinzara - Appreciate the contribution here but I don't think we're going to pursue this feature at this time. The `Auth0` class is likely to see a re-write in the future to make an action like this easier to handle in your application.

**Pull request closed without merging**
