### PR TITLE
Throw InvalidTokenException instead of RuntimeException when parsing malformed token (fix #438)

### LINKED ISSUE #438: TokenVerifier::verify throws a \RuntimeException instead of an InvalidTokenException
Hello !

### Description

Providing an invalid JSON body to the token result in `\RuntimeException` instead of `InvalidTokenException`. For example:

image

### Environment

- **Version of this library used:** 7.20
- **Other modules/plugins/libraries that might be involved:** lcobucci/jwt:3.3.2

### PR DESCRIPTION
**Pull request by B-Galati**
Hello !

### Description

Fix #438 

### Testing

- [x] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by B-Galati** [comment]
@joshcanhelp Hello! Is the CI broken?

**Comment by lbalmaceda** [comment]
The configuration looks good. Let me try to kick the build.

**Comment by lbalmaceda** [comment]
Looks like these integration tests need valid credentials to be set up in order for them to run. Sadly, I won't be able to provide them. Let me reach out to the team.

**Comment by B-Galati** [comment]
Thanks @lbalmaceda :pray:

**Comment by B-Galati** [comment]
@lbalmaceda @joshcanhelp friendly ping :pray:

**Comment by lbalmaceda** [comment]
@B-Galati apologies for missing the follow-up. We're tracking the refactor of those tests that require client_secret _internally_ as `SDK-1751` and will be picking it up the next week. After that's fixed, we can rebase this PR and checks should pass.

**Comment by jimmyjames** [comment]
I've verified these changes locally, so going to bypass checks to not block this PR any longer. We will be doing some refactoring to better enable tests running on PRs. Thanks for your patience!

**Pull request merged**
