### PR TITLE
Authentication API, support for signup/ch.pwd

### LINKED ISSUE #121: Add signup
The [dbconnections/signup](https://auth0.com/docs/api/authentication#!#post--dbconnections-signup) is missing in the SDK;

> This as originally asked at https://auth0.com/forum/t/dbconnections-signup-endpoint-missing-in-the-php-sdk/4435

### PR DESCRIPTION
**Pull request by remuslazar**
This PR implements both Authentication API endpoints [dbconnections/signup](https://auth0.com/docs/api/authentication#!#post--dbconnections-signup) and [dbconnections/change_password](https://auth0.com/docs/api/authentication#!#post--dbconnections-change_password).

An additional Unit-Test is also included but this should be reworked, see my comment below.

Resolves #121

### CODE REVIEW

**Comment by remuslazar** [comment]
@glena as I mentioned in the PR desc., the Unit-Test should implement a fixture to cleanup the Auth0 DB in setUp(), I'm not sure if using the Management API will be the right approach? Another issue is the `change_password` Test, is there an email available for such scenarios? I put my own email while running the tests locally, prior to the commit I changed the configured email to "unit.test@auth0.com" as a kind-of placeholder..

How does travis deal with the right environment vars like `APP_CLIENT_ID` etc.?

**Comment by glena** [comment]
Dont worry about the tests, I need to rebuild part of it an mock the api calls to get rid of failures due to rate limits.

I will check the PR, really appreaciated :)

**Comment by remuslazar** [comment]
@glena you're welcome, thank you for the awesome Auth0 service:)

I just tweaked the tests to use a random email, so this should run ok now. I think the test database will be purged from time to time, right? At least I saw other tests creating stuff with random ids etc..

**Comment by remuslazar** [comment]
@glena ok, now my test should be just fine, the test suite failing on exact same step as on master:)

**Pull request merged**
