### PR TITLE
Add support for guzzle ^6.0 (or ^7.0)

### PR DESCRIPTION
**Pull request by marko-ilic**
This PR adds support for guzzle 6.0. 
Forcing guzzle 7.2 can be a problem in different libs, and version 6.x works fine with php 8

### CODE REVIEW

**Comment by evansims** [comment]
Hey, @marko-ilic 👋 Thanks for your suggestion. I'll take a look at this next week and see if it's viable.

**Comment by everettgreen-cricut** [comment]
> Hey, @marko-ilic 👋 Thanks for your suggestion. I'll take a look at this next week and see if it's viable.

For what it's worth, we're working to use this with Magento 2 at the moment and having to work around this issue because Magento 2 still depends on Guzzle ^6.3.3. Would appreciate supporting Guzzle 6 if it's compatible!

**Review by evansims — APPROVED** [review]

**Comment by evansims** [comment]
@marko-ilic Everything looks good from my tests here! If you'd be so kind as to bring your branch up to date with master I can merge these in for the next release. Thanks!

**Comment by everettgreen-cricut** [comment]
@evansims - thanks for getting this merged in! I'm not familiar with the release cadence - do you have an estimate for when 7.9.0 might be released?

**Pull request merged**
