### PR TITLE
Adopt PSR2 Code Styling

### PR DESCRIPTION
**Pull request by Nyholm**
I think we should use a coherent code style of this library. We already adopted PSR7 and PSR16. Lets work with [PSR2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) as well. 

This PR is generated with PSR2 cs fixer. 

We should merge this and then enable [StyleCI](https://styleci.io/) to make sure all future PRs will follow the styles.

### CODE REVIEW

**Comment by cocojoe** [comment]
@glena you have any strong thoughts on this? Personally I prefer inline curly bracket for classes.  However that is just me 😄 It would be good to adhere to a general style guideline as we do with other SDKS.

**Comment by Nyholm** [comment]
I do really like one-line if statements and if statements without brackets... But I gave all that up for a common standard =)

**Comment by glena** [comment]
✅ I do really like one-line if statements
❌ if statements without brackets (believe it or not, people forget to add the braces when they add a second line...)

hahaha, yes I don't like things from PSR-2, but sounds good implementing it since it will make easier for people to contribute.

Lets merge it

**Comment by Nyholm** [comment]
Thank you for merging. Make sure to enable StyleCi

**Pull request merged**
