### PR TITLE
Changed Token::getClaims() to Token::claims()->get()

### LINKED ISSUE #621: PR to fix deprecation notice to use Token::claims()->get()
### SDK Version

7.5

### PHP Version

Other (specify in 'additional context')

### Composer Version

2.x

### What happened?

When we decode a token that has an array of audiences it gives us the following deprecation notice:

```You will only get the first array entry as a string. Use Token::claims()->get() instead.```

This is triggered by `\Lcobucci\JWT\Token:236`.

### How can we reproduce this issue?

Checkout tag 7.5.0 and validate a token with `aud` as an array

### Additional context

Due to the age of our app, and the inability to update to later packages, it's impossible for us to get rid of this slight hindrance. In prod, error's aren't reported so it's not a problem, but on local, it breaks anything that required authentication, due to the json return not being valid.

I want to know if it would be frowned upon if I create a PR to fix this in a minor release for 7.5.x. Would this be possible and can it be released as 7.5.1 if I make a pr to the 7.5 tag or would this cause more headaches for you than it's worth?

Thanks for taking the time to read.

### PR DESCRIPTION
**Pull request by Bird87ZA**
### Changes

Change `Token::getClaims()` to `Token::claims()->get()` to prevent a deprecation warning from showing up.

### References

Resolves #621

### Testing

When you run this and pass an array of tokens, you should not receive the deprecation notice regarding `Tokens::getClaims`.

### Contributor Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

### CODE REVIEW

**Comment by evansims** [comment]
Hi @Bird87ZA 👋 Seems builds are failing, can you try running this through the test suite (`composer run tests`) on your machine and see if it's successful?

Also, could you please run `composer show -i` from the project directory you've been seeing this deprecation warning from, and share your output? I want to make sure our dependency versions line up.

**Comment by Bird87ZA** [comment]
When I run `composer run tests` it fails with an error:

```
composer run tests

In RunScriptCommand.php line 98:
                                                 
  Script "tests" is not defined in this package  
                                                 

run-script [--timeout TIMEOUT] [--dev] [--no-dev] [-l|--list] [--] [<script> [<args>...]]
```

Composer version is 2.3.5, I'll check it out.

And don't judge me. It's not my company and I'm working on getting this sorted out 😂 

https://gist.github.com/Bird87ZA/b0a5ef17966a4ae3cb24288acdfd31b4

**Comment by Bird87ZA** [comment]
I'm having a hard time getting the tests to run on my local. I've added my `.env` variables, but not sure if they are correct. Is there somewhere I can get test values or do I use my dev variables.

**Comment by evansims** [comment]
Haha, no judgement here, contributions are always appreciated!

So, I apologize, but I'm just now realizing that your project is using a *really* old version of the PHP SDK from 2020, with 7.9.2 being the most recent version. I'm assuming they did not upgrade because of the JWT dependency. Your project manifest is relying on `lcobucci/jwt` on `3.4.6`. However, the v7 branch of the SDK was updated in 7.6.0 to use a fork of that dependency pinned at a special 3.3.4 release to backport PHP 8 support.

In this case my suggestion would be, since you already have a fork up and running with your fix, to pin this fork of yours in your project's composer manifest using the commit tag.

**Comment by evansims** [comment]
Apologies for the confusion, that was entirely my fault on the misunderstanding. Thank you for your work here, at any rate!

**Pull request closed without merging**
