### PR TITLE
Make RedirectUri accessible outside the Auth0 class

### PR DESCRIPTION
**Pull request by mijohansen**
### Changes

Added getters and setters to Auth0 $redirectUri

### CODE REVIEW

**Comment by joshcanhelp** [comment]
@mijohansen - Appreciate the contribution here! Can you give me a little more info on why you need this?

**Comment by mijohansen** [comment]
I want to access this to use it in a psr7 middleware. This way the middleware just can take the Auth0 object and figure get the redirect uri from that config.

**Comment by joshcanhelp** [comment]
@mijohansen - I'm wondering if it might be best to just use the `Authentication` class directly for your purposes if you're building your own authorize URLs.

**Comment by mijohansen** [comment]
I’m not building my own urls. I just want to match the current url to the redirect-url, without needing to pass it manually to my functions.

**Comment by joshcanhelp** [comment]
@mijohansen - The redirect URL is the callback URL, where the login is processed. That can't be dynamic as it needs to be registered with your Auth0 Application. If you're trying to get users back to a specific place in your application after logging in, you'll need to do that a different way.

**Comment by mijohansen** [comment]
I want to do something like this:
```php
        if ($request->getUri()->getPath() === $auth0->getRedirectPath()) {
            $auth0->exchange();
            return send_redirect($response, $_SESSION["REDIRECT_AFTER_LOGIN"]);
        } 
    }
```

**Comment by joshcanhelp** [comment]
How many callback URLs will you have in your application? Typically you won't need more than one, in which case you can store that in a constant or env variable. You'll need that value to initialize the `Auth0` class so that value you use there could be used here as well:

```
if ($request->getUri()->getPath() === AUTH0_CALLBACK_PATH) {
    $auth0->exchange();
    return send_redirect($response, $_SESSION["REDIRECT_AFTER_LOGIN"]);
} 
```

Your way might make more sense if there were many different callback URLs or they were dynamic but because they are exact match and registered ahead of time, I don't think this is necessary.

**Comment by mijohansen** [comment]
Ok. nevermind.

**Pull request closed without merging**
