### PR TITLE
docs: Correct instructions for management configuration strategy

### PR DESCRIPTION
**Pull request by fullstackfool**
Clarify docs when using management configuration strategy.

### Contributor Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

### CODE REVIEW

**Review by evansims — APPROVED** [review]
Hey, @fullstackfool 👋  Thanks for your contribution, good catch. Made some minor edits.

**Comment by fullstackfool** [comment]
Hi, @evansims!

The SdkConfiguration logic does not seem to match your edit:

https://github.com/auth0/auth0-PHP/blob/cbf8565555f9d78ce686bfeee303db1010bd1927/src/Configuration/SdkConfiguration.php#L528-L543

**Comment by evansims** [comment]
@fullstackfool I'm not sure I follow. A domain is required, and either a Management Token must be assigned, or a Client ID and Client Secret need to be provided in the absense of one. Can you clarify?

**Comment by fullstackfool** [comment]
> @fullstackfool I'm not sure I follow. A domain is required, and either a Management Token must be assigned, or a Client ID and Client Secret need to be provided in the absense of one. Can you clarify?

You're absolutely right - still early here! Thank you for the edit.

**Pull request merged**
