### PR TITLE
Removed deprecated functions and classes

### LINKED ISSUE #161: Remove deprecated functions and classes
This issue is just a friendly reminder that we should remove all deprecated function before tagging a new major release

### PR DESCRIPTION
**Pull request by Nyholm**
Fixes #161

### CODE REVIEW

**Comment by cocojoe** [comment]
hey @Nyholm can you squash/fixup your commits on this and also provide in the first comment a summary of the BCs.

Thanks

**Comment by Nyholm** [comment]
Since the first of April this year, you can do that when merging. You can select "squash and merge" and then modify the commit message. 

If this is disabled for you then an Admin to this repo can enable it under the settings. (It is enabled by default)

**Comment by cocojoe** [comment]
heh yes I know this, if a PR is a mess I will just squash it for the headline.  If the PR has a nice concise commit history I'll keep it 😄

**Comment by Nyholm** [comment]
Consider this PR a mess. Feel free to squash it when merging. =)

**Comment by Nyholm** [comment]
Oh, I see there is some conflicts now. I can fix it

**Pull request merged**
