### PR TITLE
Added support for PSR simple cache adapters

### LINKED ISSUE #160: Removed the CacheHelper interface
We should use PSR16 instead. 

This would be a BC break.

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #160 
It feels so good to remove code =)

### usage 

```php
$cache = AcmeSimpleCache(); // Any simple cache implementation. Example from php-cache.com
$fetcher = new JWKFetcher($cache);
```

### CODE REVIEW

**Comment by cocojoe** [comment]
How come min PHP version for testing has sneakily gone from 5.5 to 5.6 ? 😄

**Comment by Nyholm** [comment]
Sorry, I did not mean to be sneaky. =)

php-cache/array adapter does not support PHP5.5. (See [travis build](https://travis-ci.org/auth0/auth0-PHP/builds/248019778?utm_source=github_status&utm_medium=notification)). That is why I bumped it.

**Comment by cocojoe** [comment]
This looks good, doesn't seem to be much point in writing your own caching system when you can simply bolt one on a [Cache Adapters](http://www.php-cache.com/en/latest/)

The 5.5 to 5.6 should be fine (I see PHPUnit pushes this as well).  5.x.x will be the security/maintenance branch.

**Comment by cocojoe** [comment]
Can you add some usage examples to PR so we can use these in documentation later. Thx

**Comment by Nyholm** [comment]
Sure. Thank you for the review.

**Pull request merged**
