### PR TITLE
Fixing issue with Guzzle options being ignored.

### PR DESCRIPTION
**Pull request by garnold**

### CODE REVIEW

**Comment by garnold** [comment]
Build seems to be failing due to missing environment variables. Any help with how to fix that would be greatly appreciated.

**Comment by garnold** [comment]
@glena @cocojoe @Nyholm Are you able to take a look?

**Comment by Nyholm** [comment]
I did check yesterday. I've actually no idea.

The secret travis test has always been a bit.. secret for me.

**Comment by garnold** [comment]
@Nyholm Ok, thanks for taking a look.

This pull fixes a nasty/silent bug, so if you're able to merge it would be greatly appreciated.

**Comment by glena** [comment]
released as 5.0.5

thx for your contribution

**Pull request merged**
