### PR TITLE
Added style CI config

### PR DESCRIPTION
**Pull request by Nyholm**
Lets make the code more readable. 

An admin should:
1. Merge this PR
2. Enable https://styleci.io/
3. Create first analysis in style-ci admin
4. Create a PR with fixes from Style-Ci admin

### CODE REVIEW

**Comment by glena** [comment]
Not posible since StyleCI ask for permissions to access private repos too and you cant opt out them.

**Comment by Nyholm** [comment]
Are you sure? I know @GrahamCampbell does not like applications that ask for private repos.

**Comment by GrahamCampbell** [comment]
> Not posible since StyleCI ask for permissions to access private repos too and you cant opt out them.

Nope. It strictly only asks for public repos. You have to opt-in to private repos.

**Comment by Nyholm** [comment]
Ping @glena?

**Pull request closed without merging**
