### PR TITLE
Mark all classes as final

### LINKED ISSUE #162: Make as many classes as we can final
We should also use `private` instead of `protected` as much as we can.

### PR DESCRIPTION
**Pull request by Nyholm**
I marked all classes as final. This will make it easer for us to make changes that does not break BC. 

It may seam weird. But we can always remove the `final` keyword later but we cannot *add* it

This will fix #162

### CODE REVIEW

**Comment by cocojoe** [comment]
@glena LGTM I think it's good to help mitigate BC in future by avoiding subclasses.

**Comment by glena** [comment]
👍

**Comment by Nyholm** [comment]
Thank you for merging

**Comment by evansims** [comment]
> You should probably add interfaces so consumers can still mocked things during tests...

Hi @AJenbo 👋 All classes have interfaces available already.

**Pull request merged**
