### PR TITLE
Restructured tests and fixed hhvm build

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by Nyholm** [comment]
What can I do to help reviewing this?

**Comment by cocojoe** [comment]
Please rebase your commits, dont mind informative ones but `typo` doesn't really need an entry.  `git rebase -i @~2' in the branch.

**Comment by Nyholm** [comment]
I rebased the PR and squashed the commits.

**Comment by Nyholm** [comment]
#158 will fix the HHVM build error.

**Comment by cocojoe** [comment]
Is it a small fix? if so can it be moved into a new PR? The HTTP PR is for v6 and this is v5, just be nice to see all green checks :) Thx

**Comment by Nyholm** [comment]
There you go. 
Thank you for reviewing this.

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
